[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "16"
  NODE_ENV = "production"
  NPM_FLAGS = "--ignore-scripts"

[context.deploy-preview.environment]
  STORYBLOK_VERSION= "draft"

[context.production.environment]
  STORYBLOK_VERSION= "published"
  ALLOW_ROBOTS = "true"
  NEXT_PUBLIC_PLAUSIBLE = "true"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
